# Generated by Django 5.1.4 on 2025-01-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentclassinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='fathers_nid',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='fathers_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='mothers_nid',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='mothers_number',
            field=models.PositiveIntegerField(),
        ),
    ]
